import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';

// Replace this with the hash generated by the script
const MASTER_PASSWORD_HASH = '$2a$10$eZjWEiJVE5mc21CdNhSQvudM1xyCCUxC4voakIv3IPrc4wAGgfhHW';

export function authenticateToken(req, res, next) {
  const authHeader = req.headers['authorization'];
  const token = authHeader && authHeader.split(' ')[1];

  if (!token) {
    return res.status(401).json({ error: 'Authentication required' });
  }

  jwt.verify(token, process.env.JWT_SECRET, (err, user) => {
    if (err) {
      return res.status(403).json({ error: 'Invalid token' });
    }
    req.user = user;
    next();
  });
}

export function requireAdmin(req, res, next) {
  if (!req.user.isAdmin) {
    return res.status(403).json({ error: 'Admin access required' });
  }
  next();
}

// Optional authentication layer
export async function authenticateMasterPassword(req, res, next) {
  const adminPass = req.headers['x-admin-key'];
  
  if (!adminPass) {
    return next();
  }

  try {
    const isValid = await bcrypt.compare(adminPass, MASTER_PASSWORD_HASH);
    if (isValid) {
      req.isAdminAuth = true;
    }
  } catch (error) {
    console.error('Verification error:', error);
  }
  
  next();
}
